services:
  php1:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - backend

  php2:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - sqlserver
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - php1
      - php2
    networks:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - backend

volumes:
  sqlserverdata:

networks:
  backend: